созданы стили для компонента Аккордеон
js-tasks-ru/htmlcss-20211021_919869 pull request #5
Opened 2021-11-04 20:36 UTC by 919869

задание выполнено. в процессе выполнения выяснилось, что ::-webkit-details-marker с версии 89 Chrome не поддерживается и для summary устанавливается свойство display: list-item. Маркер убирается путем изменения свойства на display: block.

2021-11-04 20:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-04 20:43 UTC, GSemikozov requested changes

2021-11-04 20:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    left: 10px;
внешнее позиционирование на ровне блока не задаем

2021-11-04 20:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
это касается и марджинов

2021-11-04 20:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
советую ознакомится с вот этой статей https://dimalepel.gitbooks.io/bem-metodologiya/content/part4/chapter4-4.html

2021-11-08 19:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-10 21:28 UTC, GSemikozov approved these changes

2021-11-10 21:28 UTC, merged